### ISSUE TITLE
how to use this avro plugin?

### ISSUE THREAD

**Issue by gaolv** [AbigailBuccaneer/intellij-avro#2]
hi
Like the title. I has already add this plugin on intelij,but I do not know how to use it.
could you share me the steps?

thanks.

**Comment by AbigailBuccaneer** [comment]
Hi @gaolv.

Currently all this plugin supports is syntax highlighting of Avro IDL files. Once the plugin's installed, open an Avro IDL file or create a new file with the extension `.avdl`. It should then be syntax highlighted.

This was a project I worked on in a small amount of free time at work, and I no longer work regularly with Avro, so I'm unlikely to add any new features - but I'm always happy to receive pull requests for functionality you'd like.
